name: Publish Terraform Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform Cloud backend
      run: terraform login -token="$TF_API_TOKEN"
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'

    - name: Initialize Terraform
      run: terraform init

    - name: Format Terraform
      run: terraform fmt -check -diff

    - name: Validate Terraform
      run: terraform validate

    - name: Build package
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/swapnil-gohil/demo-repo:latest

    
