name: Publish Terraform Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'

    - name: Initialize Terraform
      run: terraform init

    - name: Format Terraform
      run: terraform fmt -check -diff

    - name: Validate Terraform
      run: terraform validate

    - name: Build package
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/swapnil-gohil/demo-repo:latest

    - name: Add badge
      run: |
        echo "[![Version](https://img.shields.io/github/package-json/v/<username>/<repo>?style=flat-square)](https://github.com/<username>/<repo>/packages)" >> README.md
        git add README.md
        git config --global user.name "swapnil-gohil"
        git config --global user.email "swapnilgohil13@gmail.com"
        git commit -m "Add version badge"
        git push

