name: Build and Publish Terraform Package

on:
  push:
    branches:
      - main

env:
  PACKAGE_NAME: Terraform
  PACKAGE_VERSION: 1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Build package
        run: |
          terraform init
          terraform validate
          terraform fmt -check
          terraform apply -auto-approve -no-color -input=false

      - name: Publish package
        uses: docker://ghcr.io/github/actions/package-docker-action:v2.0.0
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}
          tag: ${{ env.PACKAGE_VERSION }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
